<script type="text/javascript">
$(function(){
	//all hover and click logic for buttons
	$(".paginationControl a")
	.hover(
		function(){
			$(this).addClass("ui-state-hover");
		},
		function(){
			$(this).removeClass("ui-state-hover");
		}
	)
});

ajaxLoad = function(e, url) {
	var parent = $(e).parent().parent();
	parent.empty(); // clear...

	if($('#dialog')) { // kill all old dialog if present...
		$('#dialog').dialog('destroy');
		$('#dialog').remove();
	}
	wait(parent);
	parent.load(url);
};
</script>
<!--
Voir http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount > 1): ?>
<div class="paginationControl ui-helper-clearfix">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="#" onclick="ajaxLoad(this, '/liste/index/page/<?= $this->previous?>')" class="ui-state-default ui-corner-all">
    &lt; Précédent
  </a> |
<?php else: ?>
  <span class="ui-state-disabled ui-corner-all">&lt; Précédent</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
	<a href="#" onclick="ajaxLoad(this, '/liste/index/page/<?= $page?>')" class="ui-state-default ui-corner-all"><?= $page; ?></a> |
  <?php else: ?>
    <span class="ui-state-highlight ui-corner-all"><?php echo $page; ?></span> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="#" onclick="ajaxLoad(this,'/liste/index/page/<?= $this->next?>')" class="ui-state-default ui-corner-all">
    Suivant &gt;
  </a>
<?php else: ?>
  <span class="ui-state-disabled ui-corner-all">Suivant &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>